#!/usr/bin/env perl

use 5.026;
use Carp;
use charnames qw{ :full :short };
use English qw{ -no_match_vars };
use File::Spec::Functions qw{ catdir catfile };
use FindBin qw{ $Bin };
use open qw{ :encoding(UTF-8) :std };
use utf8;
use warnings;
use warnings qw{ FATAL utf8 };

## CPANM
use autodie qw{ :all };

## MIPs lib/
use lib catdir( $Bin, q{lib} );
use MIP::Cli::Mip;

our $VERSION = 0.03;

BEGIN {

    require MIP::Check::Modules;
    use MIP::Check::Modules qw{ parse_cpan_file };
    use MIP::Language::Perl qw{ check_modules_existance };

    my @modules =
      parse_cpan_file {
        cpanfile_path => catfile( $Bin, q{cpanfile} ),
      };

    ## Evaluate that all modules required are installed
    check_modules_existance(
        {
            modules_ref  => \@modules,
            program_name => $PROGRAM_NAME,
        }
    );
}

## Parse command line options
MIP::Cli::Mip->new_with_command->run();
