## MIP dependencies
# Install by running "cpanm --installdeps ." in this directory
# Module followed by minimum version required
requires qw{ Modern::Perl 1.20170117 };         # MIP
requires qw{ IPC::System::Simple 1.25 };        # MIP
requires qw{ Path::Iterator::Rule 1.012 };      # MIP
requires qw{ YAML 1.24 };                       # MIP
requires qw{ Log::Log4perl 1.49 };              # MIP
requires qw{ List::Util 1.49 };                 # MIP
requires qw{ List::MoreUtils 0.426 };           # MIP
requires qw{ Readonly 2.05 };                   # MIP
requires qw{ Try::Tiny 0.28 };                  # MIP
requires qw{ Array::Utils 0.5 };                # MIP
requires qw{ IO::Uncompress::Gunzip 2.074 };    # VEP
requires qw{ HTML::Lint 2.26 };                 # VEP
requires qw{ Archive::Zip 1.59 };               # VEP
requires qw{ Archive::Extract 0.80 };           # VEP
requires qw{ DBI 1.637 };                       # VEP
requires qw{ JSON 2.97000 };                    # VEP
requires qw{ DBD::mysql 4.043 };                # VEP
requires qw{ CGI 4.37 };                        # VEP
requires qw{ Sereal::Encoder 4.004 };           # VEP
requires qw{ Sereal::Decoder 4.004 };           # VEP
requires qw{ Bio::Root::Version 1.007002 };     # VEP
requires qw{ Module::Build 0.4224 };            # VEP
requires qw{ File::Copy::Recursive 0.38 };      # VEP
