## MIP dependencies
# Install by running "cpanm --installdeps ." in this directory
# Module followed by minimum version required
requires qw{ Archive::Extract 0.80 };               # VEP
requires qw{ Archive::Zip 1.59 };                   # VEP
requires qw{ Array::Utils 0.5 };                    # MIP
requires qw{ Bio::Root::Version 1.007002 };         # VEP
requires qw{ CGI 4.37 };                            # VEP
requires qw{ Clone 0.39 };                          # MIP
requires qw{ Data::Diver 1.0101 };                  # MIP
requires qw{ Data::Printer 0.40 };                  # MIP
requires qw{ DB_File 1.840 };                       # STAR-Fusion
requires 'DBD::mysql', '== 4.043';                    # VEP
requires qw{ DBI 1.637 };                           # VEP
requires qw{ DB_File 1.840 };                       # STAR-Fusion
requires qw{ Email::Valid 1.202 };                  # MIP
requires qw{ File::Copy::Recursive 0.38 };          # VEP
requires qw{ File::Find::Rule 0.34 };               # MIP
requires qw{ HTML::Lint 2.26 };                     # VEP
requires qw{ IO::Interactive 1.022 };               # MIP
requires qw{ IO::Uncompress::Gunzip 2.074 };        # VEP
requires qw{ IPC::System::Simple 1.25 };            # MIP
requires qw{ JSON 2.97000 };                        # VEP
requires qw{ JSON::XS 3.02 };                       # STAR-Fusion
requires qw{ List::MoreUtils 0.413 };               # MIP
requires qw{ List::Util 1.49 };                     # MIP
requires qw{ Log::Log4perl 1.49 };                  # MIP
requires qw{ Modern::Perl 1.20170117 };             # MIP
requires qw{ Module::Build 0.4224 };                # VEP
requires qw{ Module::CPANfile 1.1002 };             # MIP
requires qw{ Moose::Util::TypeConstraints 2.2010 }; # MIP
requires qw{ MooseX::App 1.39 };                    # MIP
requires qw{ MooseX::Types::Moose 0.50 };           # MIP
requires qw{ MooseX::Types::Structured 0.36 };      # MIP
requires qw{ Path::Iterator::Rule 1.012 };          # MIP
requires qw{ PerlIO::gzip 0.20 };                   # VEP
requires qw{ Readonly 2.05 };                       # MIP
requires qw{ Sereal::Decoder 4.004 };               # VEP
requires qw{ Sereal::Encoder 4.004 };               # VEP
requires qw{ Set::IntervalTree 0.11};               # MIP
requires qw{ Test::Trap };                          # MIP
requires qw{ Text::WagnerFischer 0.04 };            # MIP
requires qw{ Try::Tiny 0.28 };                      # MIP
requires qw{ URI::Escape 3.31 };                    # STAR-Fusion
requires qw{ YAML 1.24 };                           # MIP
