---
config_file:
  associated_recipe:
    - mip
  data_type: SCALAR
  default: 0
  type: path
  update_path: absolute_path
container_manager:
  associated_recipe:
    - mip
  data_type: SCALAR
  default: singularity
  type: mip
custom_default_parameters:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - program_test_file
    - select_programs
    - skip_programs
  type: mip
environment_name:
  associated_recipe:
    - mip
  data_type: SCALAR
  default: mip
  mandatory: no
  type: mip
pipelines:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - rd_dna
    - rd_rna
  mandatory: no
  type: mip
program_test_file:
  associated_recipe:
    - mip
  data_type: SCALAR
  type: path
  update_path: absolute_path
quiet:
  associated_recipe:
    - mip
  data_type: SCALAR
  exists_check: directory
  mandatory: no
  type: mip
reference_dir:
  associated_recipe:
    - mip
  data_type: SCALAR
  exists_check: directory
  mandatory: no
  type: path
  update_path: absolute_path
rd_dna:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - bedtools
    - bwa
    - bwakit
    - bwa-mem2
    - cadd
    - chanjo
    - chromograph
    - cnvnator
    - cyrius
    - deepvariant
    - deeptrio
    - delly
    - expansionhunter
    - fastqc
    - gatk
    - gatk4
    - genmod
    - glnexus
    - htslib
    - manta
    - mip
    - mip_scripts
    - multiqc
    - peddy
    - picard
    - plink
    - python
    - rhocall
    - rtg-tools
    - sambamba
    - smncopynumbercaller
    - stranger
    - svdb
    - telomerecat
    - tiddit
    - ucsc
    - upd
    - varg
    - vcf2cytosure
    - vcfanno
    - vep
  mandatory: no
  type: mip
rd_rna:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - arriba
    - blobfish
    - bootstrapann
    - fastqc
    - gatk4
    - gffcompare
    - htslib
    - megafusion
    - mip
    - mip_scripts
    - multiqc
    - pdfmerger
    - picard
    - preseq
    - python
    - rseqc
    - salmon
    - star
    - star-fusion
    - stringtie
    - svdb
    - trim-galore
    - ucsc
    - utilities
    - vep
  mandatory: no
  type: mip
container:
  associated_recipe:
    - mip
  data_type: HASH
  mandatory: no
  type: mip
select_programs:
  associated_recipe:
    - mip
  data_type: ARRAY
  mandatory: no
  type: mip
skip_programs:
  associated_recipe:
    - mip
  data_type: ARRAY
  mandatory: no
  type: mip
test_mode:
  associated_recipe:
    - mip
  data_type: SCALAR
  mandatory: no
  type: mip
vep_assemblies:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - GRCh37
    - GRCh38
  type: mip
vep_auto_flag:
  associated_recipe:
    - mip
  data_type: SCALAR
  default: cfp
  type: mip
vep_cache_dir:
  associated_recipe:
    - mip
  data_type: SCALAR
  mandatory: no
  type: path
  update_path: absolute_path
vep_plugins:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - dbNSFP
    - ExACpLI
    - LoFtool
    - MaxEntScan
    - SpliceAI
  mandatory: no
  type: mip
vep_species:
  associated_recipe:
    - mip
  data_type: ARRAY
  default:
    - homo_sapiens_merged
  type: mip
