---
clusterConstantPath: /mnt/hds/proj/cust003/develop
analysisConstantPath: analysis
analysisType: exomes
javaUseLargePages: yes
outScriptDir: CLUSTERCONSTANTPATH!/ANALYSISTYPE!_scripts
GATKBaseReCalibrationSNPKnownSet: dbsnp_138.b37.vcf
GATKDownSampleToCoverage: 1000
GATKHaploTypeCallerSNPKnownSet: dbsnp_138.b37.vcf
GATKReAlignerINDELKnownSet1: 1000G_phase1.indels.b37.vcf
GATKReAlignerINDELKnownSet2: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKVariantEvalDbSNP: dbsnp_138.b37.excluding_sites_after_129.vcf
GATKVariantEvalGold: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKVariantReCalibrationTSFilterLevel: 99.9
GATKVariantReCalibrationTrainingSet1000GOmni: 1000G_omni2.5.b37.sites.vcf
GATKVariantReCalibrationTrainingSetDbSNP: dbsnp_138.b37.vcf
GATKVariantReCalibrationTrainingSetHapMap: hapmap_3.3.b37.sites.vcf
GATKVariantReCalibrationTrainingSetMills: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKGenoTypeGVCFsRefGVCF: Merged_reference_infiles.gvcf
instanceTag:
  - CMMS
aligner: bwa
QCCollectRegExpFile: qc_regExp_v1.3.yaml
QCCollectSampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
annovarGenomeBuildVersion: hg19
annovarMAFThreshold: 0
annovarPath: CLUSTERCONSTANTPATH!/modules/annovar
annovarTableNames:
  - refGene
chanjoBuildDb: CCDS.current.txt
chanjoAnnotateCutoff: 10
dryRunAll: 0
genomeAnalysisToolKitPath: CLUSTERCONSTANTPATH!/modules/GenomeAnalysisTK-3.4-46
humanGenomeReference: Homo_sapiens.GRCh37.d5.fasta
inScriptDir: CLUSTERCONSTANTPATH!/modules/MIP
maximumCores: 16
mosaikBuildMedianFragLength: 375
outDataDir: CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!
pBwaAln: 0
pBwaMem: 1
pBwaSampe: 0
pChanjoBuild: 1
pChanjoAnnotate: 1
pChanjoImport: 0
pChanjoSexCheck: 1
pFastQC: 1
pGATKBaseRecalibration: 1
pGATKHaploTypeCaller: 1
pGATKGenoTypeGVCFs: 1
pGATKRealigner: 1
pGATKVariantEvalAll: 1
pGATKVariantEvalExome: 1
pGATKVariantRecalibration: 1
pGZipFastq: 1
pGenomeCoverageBED: 1
pMosaikAlign: 0
pMosaikBuild: 0
pPicardToolsCalculateHSMetrics: 1
pPicardToolsCollectMultipleMetrics: 1
pPicardToolsMarkduplicatesWithMateCigar: 1
pPicardToolsMergeRapidReads: 0
pPicardToolsMergeSamFiles: 1
pQCCollect: 1
pRCovPlots: 0
pRankVariants: 1
pRemoveRedundantFiles: 1
pSampleCheck: 1
pedigreeFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_pedigree.txt
picardToolsPath: CLUSTERCONSTANTPATH!/modules/picard-tools-1.137
projectID: cust003
pythonVirtualEnvironment: virtenv_develop.py.2.7
referencesDir: CLUSTERCONSTANTPATH!/references
researchEthicalApproval: notApproved
sampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
writeConfigFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_config.yaml
GenomeCoverageBEDMaxCoverage: 30
vepDirectoryPath: CLUSTERCONSTANTPATH!/modules/ensembl-tools-release-81/scripts/variant_effect_predictor
vepDirectoryCache:  CLUSTERCONSTANTPATH!/modules/ensembl-tools-release-81/cache
vcfParserVepTranscripts: 1
vcfParserRangeFeatureFile: cust000-Research.txt
vcfParserRangeFeatureAnnotationColumns: 
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
vcfParserSelectFile: cust000-Clinical_master_list.txt
vcfParserSelectFileMatchingColumn: 3
vcfParserSelectFeatureAnnotationColumns:
  - 3
  - 10
  - 11
  - 14
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
snpEffPath: CLUSTERCONSTANTPATH!/modules/snpEff.v4.1
snpSiftAnnotationFiles:
  dbsnp_138.b37.excluding_sites_after_129.vcf.gz: CAF
  ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz: AF
  clinvar_20150901.vcf.gz: CLNSIG,CLNACC
  ExAC.r0.3.sites.vep.vcf.gz: AF
snpSiftDbNSFPAnnotations:
  - SIFT_score
  - SIFT_pred
  - Polyphen2_HVAR_score
  - Polyphen2_HVAR_pred
  - MutationTaster_score
  - MutationTaster_pred
  - FATHMM_score
  - FATHMM_pred
  - Reliability_index
  - GERP++_RS
  - GERP++_NR
  - phyloP46way_primate
  - phyloP100way_vertebrate
  - phastCons46way_primate
  - phastCons100way_vertebrate
  - SiPhy_29way_logOdds
  - MutationAssessor_score
  - MutationTaster_pred
genmodModelsFamilyType: cmms
caddWGSSNVs: 1
caddWGSSNVsFile: whole_genome_SNVs.v1.3_ge10.tsv.gz
cadd1000Genomes: 1
rankModelFile: rank_model_cmms_v1.6.ini
