---
clusterConstantPath: /proj/b2010080/private
analysisConstantPath: nobackup/analysis
analysisType: exomes
outScriptDir: CLUSTERCONSTANTPATH!/ANALYSISTYPE!_scripts
GATKBaseReCalibrationSNPKnownSet: dbsnp_138.b37.vcf
GATKDownSampleToCoverage: 1000
GATKExomeReferenceSNPs: all-agilent_50mb-GRCh37-SNPS_pad100_interval_list.vcf
GATKHaploTypeCallerSNPKnownSet: dbsnp_138.b37.vcf
GATKHaploTypeCallerRefBAMInfile: ReferenceBAMInfile.list
GATKReAlignerINDELKnownSet1: 1000G_phase1.indels.b37.vcf
GATKReAlignerINDELKnownSet2: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKReadBackedPhasingPhaseQualityThresh: 20
GATKVariantEvalDbSNP: dbsnp_138.b37.excluding_sites_after_129.vcf
GATKVariantEvalGold: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKVariantReCalibrationNumBadVariants: 3000
GATKVariantReCalibrationTSFilterLevel: 99.9
GATKVariantReCalibrationTrainingSet1000GOmni: 1000G_omni2.5.b37.sites.vcf
GATKVariantReCalibrationTrainingSetDbSNP: dbsnp_138.b37.vcf
GATKVariantReCalibrationTrainingSetHapMap: hapmap_3.3.b37.sites.vcf
GATKVariantReCalibrationTrainingSetMills: Mills_and_1000G_gold_standard.indels.b37.vcf
instanceTag: CMMS
ImportantDbFile: dbCMMS.v1.0.txt
ImportantDbFileOutFile: 'CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!/FDN!/ALIGNER!/GATK/candidates/ranking/FDN!_orphan.selectVariants,CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!/FDN!/ALIGNER!/GATK/candidates/ranking/clinical/FDN!.selectVariants'
ImportantDbMasterFile: CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!.intersectCollect_selectVariants_db_master.txt
ImportantDbTemplate: select_dbCMMS_variants_db_master.txt
MIP: 1
aligner: mosaik
QCCollectRegExpFile: qc_regexp.yaml
QCCollectSampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
annovarGenomeBuildVersion: hg19
annovarMAFThreshold: 0
annovarPath: CLUSTERCONSTANTPATH!/modules/annovar
annovarSupportedTableNames: 0
annovarTableNames: 'refGene,mce46way,gerp++elem,segdup,tfbs,mirna,snp137NonFlagged,1000g2012apr_all,esp6500si_all,ljb2_sift,ljb2_pp2hdiv,ljb2_pp2hvar,ljb2_mt,ljb2_lrt,ljb2_gerp++,ljb2_phylop,clinvar_20131105'
chanjoBuildDb: CCDS.current.txt
chanjoCalculateCutoff: 10
dryRunAll: 0
email: 0
genomeAnalysisToolKitPath: CLUSTERCONSTANTPATH!/modules/GenomeAnalysisTK-2.8-1
humanGenomeReference: Homo_sapiens.GRCh37.d5.fasta
inScriptDir: CLUSTERCONSTANTPATH!/mip_scripts_master
maximumCores: 16
mergeAnnotatedVariantsTemplateFile: CMMS_intersectCollect_db_master_template.txt
mosaikBuildMedianFragLength: 375
outDataDir: CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!
pAddDepth: 1
pAnnovar: 1
pBwaAln: 0
pBwaMem: 0
pBwaSampe: 0
pCalculateCoverage: 1
pChanjoBuild: 1
pChanjoCalculate: 1
pChanjoImport: 0
pCoverageBED: 1
pFastQC: 1
pGATKBaseRecalibration: 1
pGATKHaploTypeCaller: 1
pGATKHaploTypeCallerCombineVariants: 1
pGATKPhaseByTransmission: 1
pGATKReadBackedPhasing: 1
pGATKRealigner: 1
pGATKVariantEvalAll: 1
pGATKVariantEvalExome: 1
pGATKVariantRecalibration: 1
pGZip: 1
pGenomeCoverageBED: 1
pMergeAnnotatedVariants: 1
pMosaikAlign: 1
pMosaikBuild: 1
pPicardToolsCalculateHSMetrics: 1
pPicardToolsCollectMultipleMetrics: 1
pPicardToolsMarkduplicates: 1
pPicardToolsMergeRapidReads: 0
pPicardToolsMergeSamFiles: 1
pQCCollect: 1
pQaCompute: 1
pRCovPlots: 0
pRankVariants: 1
pRemovalRedundantFiles: 1
pPicardToolsSort: 1
pSampleCheck: 1
pedigreeFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_pedigree.txt
picardToolsPath: CLUSTERCONSTANTPATH!/modules/picard-tools-1.106
projectID: b2010080
pythonVirtualEnvironment: virtualenv.py.2.7
rankScore: -100
referencesDir: CLUSTERCONSTANTPATH!/mip_references
sampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
writeConfigFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_config.yaml
xCoverage: 30
