---
clusterConstantPath: /proj/b2010080/private
analysisConstantPath: nobackup/analysis
analysisType: exomes
outScriptDir: CLUSTERCONSTANTPATH!/ANALYSISTYPE!_scripts
GATKBaseReCalibrationSNPKnownSet: dbsnp_138.b37.vcf
GATKDownSampleToCoverage: 1000
GATKExomeReferenceSNPs: all-agilent_50mb-GRCh37-SNPS_pad100_interval_list.vcf
GATKHaploTypeCallerSNPKnownSet: dbsnp_138.b37.vcf
GATKReAlignerINDELKnownSet1: 1000G_phase1.indels.b37.vcf
GATKReAlignerINDELKnownSet2: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKReadBackedPhasingPhaseQualityThresh: 20
GATKVariantEvalDbSNP: dbsnp_138.b37.excluding_sites_after_129.vcf
GATKVariantEvalGold: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKVariantReCalibrationTSFilterLevel: 99.9
GATKVariantReCalibrationTrainingSet1000GOmni: 1000G_omni2.5.b37.sites.vcf
GATKVariantReCalibrationTrainingSetDbSNP: dbsnp_138.b37.vcf
GATKVariantReCalibrationTrainingSetHapMap: hapmap_3.3.b37.sites.vcf
GATKVariantReCalibrationTrainingSetMills: Mills_and_1000G_gold_standard.indels.b37.vcf
GATKGenoTypeGVCFsRefGVCF: Merged_reference_infiles.gvcf
instanceTag: CMMS
MIP: 1
aligner: mosaik
QCCollectRegExpFile: qc_regexp.yaml
QCCollectSampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
annovarGenomeBuildVersion: hg19
annovarMAFThreshold: 0
annovarPath: CLUSTERCONSTANTPATH!/modules/annovar
annovarSupportedTableNames: 0
annovarTableNames:
  - refGene
  - mce46way
  - gerp++elem
  - segdup
  - tfbs
  - mirna
  - snp137NonFlagged
  - 1000g2012apr_all
  - esp6500si_all
  - ljb2_sift
  - ljb2_pp2hdiv
  - ljb2_pp2hvar
  - ljb2_mt
  - ljb2_lrt
  - ljb2_gerp++
  - ljb2_phylop
  - clinvar_20131105
chanjoBuildDb: CCDS.current.txt
chanjoCalculateCutoff: 10
dryRunAll: 0
email: 0
genomeAnalysisToolKitPath: CLUSTERCONSTANTPATH!/modules/GenomeAnalysisTK-3.2-2
humanGenomeReference: Homo_sapiens.GRCh37.d5.fasta
inScriptDir: CLUSTERCONSTANTPATH!/mip_scripts_master
maximumCores: 16
mosaikBuildMedianFragLength: 375
outDataDir: CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!
pAnnovar: 1
pBwaAln: 0
pBwaMem: 0
pBwaSampe: 0
pCalculateCoverage: 1
pChanjoBuild: 1
pChanjoCalculate: 1
pChanjoImport: 0
pCoverageBED: 1
pFastQC: 1
pGATKBaseRecalibration: 1
pGATKHaploTypeCaller: 1
pGATKGenoTypeGVCFs: 1
pGATKPhaseByTransmission: 1
pGATKReadBackedPhasing: 1
pGATKRealigner: 1
pGATKVariantEvalAll: 1
pGATKVariantEvalExome: 1
pGATKVariantRecalibration: 1
pGZip: 1
pGenomeCoverageBED: 1
pMosaikAlign: 1
pMosaikBuild: 1
pPicardToolsCalculateHSMetrics: 1
pPicardToolsCollectMultipleMetrics: 1
pPicardToolsMarkduplicates: 1
pPicardToolsMergeRapidReads: 0
pPicardToolsMergeSamFiles: 1
pQCCollect: 1
pRCovPlots: 0
pRankVariants: 1
pRemoveRedundantFiles: 1
pPicardToolsSort: 1
pSampleCheck: 1
pedigreeFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_pedigree.txt
picardToolsPath: CLUSTERCONSTANTPATH!/modules/picard-tools-1.118
projectID: b2010080
pythonVirtualEnvironment: virtualenv.py.2.7
rankScore: -100
referencesDir: CLUSTERCONSTANTPATH!/mip_references
researchEthicalApproval: approved
sampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
writeConfigFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_config.yaml
GenomeCoverageBEDMaxCoverage: 30
vepDirectoryPath: CLUSTERCONSTANTPATH!/modules/ensembl-tools-release-76/scripts/variant_effect_predictor
vepDirectoryCache:  CLUSTERCONSTANTPATH!/modules/ensembl-tools-release-76
vcfParserVepTranscripts: 1
vcfParserRangeFeatureFile: CMMS_External_Db_140114.txt
vcfParserRangeFeatureAnnotationColumns: 
  - 3
vcfParserSelectFile: dbCMMS.v1.2.txt
vcfParserSelectFileMatchingColumn: 3
vcfParserSelectFeatureAnnotationColumns:
  - 3
  - 4
  - 11
  - 15
  - 17
  - 20
  - 21
snpEffPath: CLUSTERCONSTANTPATH!/modules/snpEff
snpSiftAnnotationFiles:
  - dbsnp_138.b37.excluding_sites_after_129.vcf
  - dbsnp_138.b37.vcf
  - 1000G_phase1.indels.b37.vcf
  - 1000G_phase1.snps.high_confidence.b37.vcf
  - ESP6500SI-V2-SSA137.updatedProteinHgvs.snps_indels.vcf
  - clinvar_20140902.vcf
snpSiftDbNSFPAnnotations:
  - SIFT_score
  - SIFT_pred
  - Polyphen2_HVAR_score
  - Polyphen2_HVAR_pred
  - LRT_score
  - LRT_pred
  - MutationTaster_score
  - MutationTaster_pred
  - FATHMM_score
  - FATHMM_pred
  - RadialSVM_score
  - RadialSVM_pred
  - LR_score
  - LR_pred
  - Reliability_index
  - GERP++_RS
  - GERP++_NR
  - phyloP46way_primate
  - phyloP100way_vertebrate
  - phastCons46way_primate
  - phastCons100way_vertebrate
  - SiPhy_29way_logOdds
  - MutationAssessor_score
  - MutationTaster_pred
caddWGSSNVs: 1
cadd1000Genomes: 1
