---
## Environment
analysis_constant_path: analysis
max_cores_per_node: 36
node_ram_memory: 180
project_id: test
load_env:
  MIP_rd_rna:
    method: conda
    mip:
slurm_quality_of_service: low
## Input
pedigree_file: cluster_constant_path!/case_id!/case_id!_pedigree.yaml
reference_dir: cluster_constant_path!/references
fusion_select_file: cluster_constant_path!/case_id!/grch38_gene_panels.bed
vcfparser_select_file: cluster_constant_path!/case_id!/gene_panels.bed
## Output
config_file_analysis: cluster_constant_path!/case_id!/analysis/case_id!_config.yaml
outdata_dir: cluster_constant_path!/case_id!/analysis_constant_path!
outscript_dir: cluster_constant_path!/case_id!/analysis_constant_path!/scripts
sample_info_file: cluster_constant_path!/case_id!/analysis_constant_path!/case_id!_qc_sample_info.yaml
## References
human_genome_reference: grch38_homo_sapiens_-assembly-.fasta
star_fusion_genome_lib_dir: cluster_constant_path!/references/GRCh38_gencode_v33_CTAT_lib_Apr062020.plug-n-play/ctat_genome_lib_build_dir
transcript_annotation: grch38_gencode_annotation_-v34-.gtf
gatk_haplotypecaller_snp_known_set: grch38_dbsnp_-146-.vcf.gz
gatk_baserecalibration_known_sites:
  - grch38_1000g_indels_-phase1-.vcf.gz
  - grch38_dbsnp_-146-.vcf.gz
  - grch38_mills_and_1000g_-gold_standard_indels-.vcf.gz
### Analysis
## Programs
## Parameters
arriba_blacklist_path: /arriba_v1.2.0/database/blacklist_hg38_GRCh38_2018-11-04.tsv.gz
fusion_cytoband_path: /arriba_v1.2.0/database/cytobands_hg38_GRCh38_2018-02-23.tsv
fusion_proteindomain_path: /arriba_v1.2.0/database/protein_domains_hg38_GRCh38_2019-07-05.gff3
picardtools_path: /usr/picard
qccollect_sampleinfo_file: cluster_constant_path!/case_id!/analysis_constant_path!/case_id!_qc_sample_info.yaml
vep_directory_cache: cluster_constant_path!/modules/miniconda/envs/MIP_rd_rna/ensembl-tools-100/cache/
