---
## Environment
analysis_constant_path: analysis
bash_set_errexit: 1
bash_set_nounset: 0
bash_set_pipefail: 1
java_use_large_pages: 1
max_cores_per_node: 16
project_id: test
program_source_environment_command:
  gtf_file_to_feature_seqs.pl:
    - source
    - activate
    - MIP_star
module_source_environment_command:
  star_aln:
    - source
    - activate
    - MIP_star
  star_fusion:
    - source
    - activate
    - MIP_star
source_main_environment_commands:
  - source
  - activate
  - MIP_rna
slurm_quality_of_service: low
## Input
pedigree_file: cluster_constant_path!/family_id!/family_id!_pedigree.yaml
reference_dir: cluster_constant_path!/references
## Output
config_file_analysis: cluster_constant_path!/family_id!/analysis/family_id!_config.yaml
outdata_dir: cluster_constant_path!/family_id!/analysis_constant_path!
outscript_dir: cluster_constant_path!/family_id!/analysis_constant_path!/scripts
sample_info_file: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_qc_sample_info.yaml
## References
human_genome_reference: GRCh37_homo_sapiens_-d5-.fasta
### Analysis
## Programs
bootstrapann: 1
fastqc: 1
gatk_asereadcounter: 1
gatk_baserecalibration: 1
gatk_haplotypecaller: 1
gatk_splitncigarreads: 1
gatk_variantfiltration: 1
picardtools_mergesamfiles: 1
rseqc: 1
salmon_quant: 1
star_aln: 1
star_fusion: 1
## Parameters
gatk_path: cluster_constant_path!
picardtools_path: cluster_constant_path!
