---
## Environment
analysis_constant_path: analysis
bash_set_errexit: 1
bash_set_nounset: 0
bash_set_pipefail: 1
java_use_large_pages: 1
max_cores_per_node: 16
module_source_environment_command:
  pchanjo_sexcheck: "source activate mip_travis_py3"
  pfrequency_filter: "source activate mip_travis_py3"
  pmultiqc: "source activate mip_travis_py3"
  ppeddy: "source activate mip_travis_peddy"
  prankvariant: "source activate mip_travis_py3"
  psv_combinevariantcallsets: "source activate mip_travis_svdb"
  psv_rankvariant: "source activate mip_travis_py3"
  psv_varianteffectpredictor: "source activate mip_travis_vep"
  pvarianteffectpredictor: "source activate mip_travis_vep"
  pvariant_integrity: "source activate mip_travis_py3"
  pcnvnator: "source activate mip_travis_cnvnator"
project_id: travis_test
## Input
pedigree_file: cluster_constant_path!/family_id!/family_id!_pedigree.yaml
reference_dir: cluster_constant_path!/references
vcfparser_select_file: cluster_constant_path!/family_id!/aggregated_gene_panel_test.txt
sv_vcfparser_select_file: cluster_constant_path!/family_id!/aggregated_gene_panel_test.txt
## Output
config_file_analysis: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_config.yaml
outdata_dir: cluster_constant_path!/family_id!/analysis_constant_path!
outscript_dir: cluster_constant_path!/family_id!/analysis_constant_path!/scripts
sample_info_file: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_qc_sample_info.yaml
## References
gatk_genotypegvcfs_ref_gvcf: GRCh37_merged_reference_infiles_-2014-.gvcf
genmod_annotate_cadd_files:
  - GRCh37_cadd_whole_genome_snvs_ge10_-v1.3-.tsv.gz
  - GRCh37_cadd_1000g_phase3_-v1.3-.tsv.gz
  - GRCh37_cadd_exac_r0.3_-v1.3-.tsv.gz
genmod_annotate_spidex_file: GRCh37_spidex_public_noncommercial_-v1_0-.tab.gz
genmod_models_reduced_penetrance_file: GRCh37_cust003-cmms-red-pen_-2017-.tsv 
human_genome_reference: GRCh37_homo_sapiens_-d5-.fasta
rank_model_file: rank_model_cmms_-v1.19-.ini
sambamba_depth_bed: GRCh37_scout_exons_-2017-01-.bed
snpsift_annotation_files:
  GRCh37_clinvar_-2017-05-01-.vcf.gz: CLNSIG,CLNACC,CLNREVSTAT
  GRCh37_exac_reheader_-r0.3.1-.vcf.gz: AF,AF_Adj
  GRCh37_anon-swegen_str_nsphs_-1000samples-.vcf.gz: AF,AC_Hom,AC_Het,AC_Hemi
  GRCh37_loqusdb_-2016-09-26-.vcf.gz: Obs,Hom
  GRCh37_genbank_haplogroup_-2015-08-01-.vcf.gz: MTAF
sv_genmod_models_reduced_penetrance_file: GRCh37_cust003-cmms-red-pen_-2017-.tsv
sv_rank_model_file: svrank_model_cmms_-v1.1-.ini
sv_svdb_query_db_files:
  GRCh37_svdb_query_decipher_-v1.0.0-.vcf: decipher
  GRCh37_svdb_query_clingen_cgh_benign_-v1.0.0-.vcf: clingen_cgh_benign
  GRCh37_svdb_query_clingen_cgh_pathogenic_-v1.0.0-.vcf: clingen_cgh_pathogenic
  GRCh37_svdb_query_clingen_ngi_-v1.0.0-.vcf: clingen_ngi
sv_vcfannotation_header_lines_file: vcfanno_headerLines_-v1.0-.txt
sv_vcfanno_config: GRCh37_vcfanno_config_-v1.0-.toml
sv_vcfanno_lua: vcfanno_custom_-v1.0-.lua
qccollect_regexp_file: qc_regexp_-v1.15-.yaml
qccollect_sampleinfo_file: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_qc_sample_info.yaml
### Analysis
### Programs
panalysisrunstatus: 1
pbcftools_mpileup: 1
pbwa_mem: 1
pchanjo_sexcheck: 1
pcnvnator: 1
pdelly_call: 1
pdelly_reformat: 1
pendvariantannotationblock: 1
pevaluation: 1
pfastqc: 1
pfreebayes: 1
pfrequency_filter: 1
pgatk_baserecalibration: 1
pgatk_combinevariantcallsets: 1
pgatk_genotypegvcfs: 1
pgatk_haplotypecaller: 1
pgatk_variantevalall: 1
pgatk_variantevalexome: 1
pgatk_variantrecalibration: 1
pgzip_fastq: 1
pmanta: 1
pmarkduplicates: 1
pmultiqc: 1
ppeddy: 1
ppicardtools_collecthsmetrics: 1
ppicardtools_collectmultiplemetrics: 1
ppicardtools_mergesamfiles: 1
pplink: 1
pprepareforvariantannotationblock: 1
prankvariant: 1
prhocall: 1
prtg_vcfeval: 1
psamtools_subsample_mt: 1
psacct: 1
psambamba_depth: 1
psnpeff: 1
psv_combinevariantcallsets: 1
psv_rankvariant: 1
psv_reformat: 1
psv_varianteffectpredictor: 1
psv_vcfparser: 1
ptiddit: 1
pvarianteffectpredictor: 1
pvariant_integrity: 1
pvcfparser: 1
pvcf2cytosure: 1
pvt: 1
pqccollect: 1
## Parameters
frequency_genmod_filter: 1
gatk_combinevariants_prioritize_caller: gatk,bcftools,freebayes
gatk_concatenate_genotypegvcfs_bcf_file: 1
gatk_path: cluster_constant_path!
gatk_baserecalibration_disable_indel_qual: 1
gatk_haplotypecaller_no_soft_clipped_bases: 1
gatk_variantrecalibration_dp_annotation: 1
gatk_variantrecalibration_indel_max_gaussians: 1
gatk_combinevariantcallsets_bcf_file: 1
genmod_annotate_regions: 1
genmod_models_whole_gene: 1
markduplicates_picardtools_markduplicates: 1
picardtools_path: cluster_constant_path!
snpeff_ann: 1
snpeff_path: cluster_constant_path!
snpsift_annotation_outinfo_key:
  GRCh37_exac_reheader_-r0.3.1-.vcf.gz: EXAC
  GRCh37_anon-swegen_str_nsphs_-1000samples-.vcf.gz: SWEGEN
snpsift_dbnsfp_annotations:
  - GERP++_RS
  - GERP++_NR
  - phyloP46way_primate
  - phyloP100way_vertebrate
  - phastCons46way_primate
  - phastCons100way_vertebrate
sv_bcftools_view_filter: 1
sv_combinevariantcallsets_bcf_file: 1
sv_genmod_annotate_regions: 1
sv_genmod_filter: 1
sv_genmod_models_family_type: cmms
sv_rankvariant_binary_file: 1
sv_svdb_merge_prioritize: manta,delly,cnvnator,tiddit
sv_svdb_query: 1
sv_vcfanno: 1
sv_vcfparser_per_gene: 1
sv_vcfparser_select_file_matching_column: 3
sv_vcfparser_vep_transcripts: 1
sv_vt_decompose: 1
vcfparser_vep_transcripts: 1
vcfparser_select_file_matching_column: 3
vep_directory_path: cluster_constant_path!/modules/miniconda/envs/test_env/ensembl-vep/
vep_directory_cache: cluster_constant_path!/modules/miniconda/envs/test_env/ensembl-tools-91/cache/
vep_plugins_dir_path: cluster_constant_path!/modules/miniconda/envs/test_env/ensembl-tools-91/cache/
slurm_quality_of_service: low
