---
## Environment
analysis_constant_path: analysis
bash_set_errexit: 1
bash_set_nounset: 0
bash_set_pipefail: 1
java_use_large_pages: 1
max_cores_per_node: 16
project_id: test
program_source_environment_command: {}
module_source_environment_command:
source_main_environment_commands:
  - source
  - activate
  - MIP_rna
slurm_quality_of_service: low
## Input
pedigree_file: cluster_constant_path!/family_id!/family_id!_pedigree.yaml
reference_dir: cluster_constant_path!/references
## Output
config_file_analysis: cluster_constant_path!/family_id!/analysis/family_id!_config.yaml
outdata_dir: cluster_constant_path!/family_id!/analysis_constant_path!
outscript_dir: cluster_constant_path!/family_id!/analysis_constant_path!/scripts
sample_info_file: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_qc_sample_info.yaml
## References
human_genome_reference: GRCh37_homo_sapiens_-d5-.fasta
### Analysis
## Programs
pfastqc: 1
pgatk_asereadcounter: 1
pgatk_baserecalibration: 1
pgatk_haplotypecaller: 1
pgatk_splitncigarreads: 1
ppicardtools_mergesamfiles: 1
psalmon_quant: 1
pstar_aln: 1
pstar_fusion: 1
## Parameters
gatk_baserecalibration_disable_indel_qual: 1
gatk_path: cluster_constant_path!
picardtools_path: cluster_constant_path!
