---
## Environment
analysis_constant_path: analysis
load_env:
  mip_ci:
    method: conda
    mip:
max_cores_per_node: 36
node_ram_memory: 192
project_id: travis_test
slurm_quality_of_service: low
## Input
pedigree_file: cluster_constant_path!/case_id!/case_id!_pedigree.yaml
reference_dir: cluster_constant_path!/references
vcfparser_select_file: cluster_constant_path!/case_id!/aggregated_gene_panel_test.txt
## Output
config_file_analysis: cluster_constant_path!/case_id!/analysis_constant_path!/case_id!_config.yaml
outdata_dir: cluster_constant_path!/case_id!/analysis_constant_path!
outscript_dir: cluster_constant_path!/case_id!/analysis_constant_path!/scripts
sample_info_file: cluster_constant_path!/case_id!/analysis_constant_path!/case_id!_qc_sample_info.yaml
## References
gatk_genotypegvcfs_ref_gvcf: grch37_gatk_merged_reference_samples.txt
genmod_models_reduced_penetrance_file: grch37_cust003-cmms-red-pen_-2017-.tsv
human_genome_reference: grch37_homo_sapiens_-d5-.fasta
rank_model_file: rank_model_-v1.34-.ini
sambamba_depth_bed: grch37_scout_exons_-2017-01-.bed
vcfanno_config: grch37_vcfanno_config_v1.16-.toml
### Analysis
### Programs
## Parameters
fqf_annotations:
  - GNOMADAF
  - GNOMADAF_popmax
  - SWEGENAF
gatk_combinevariants_prioritize_caller: haplotypecaller
gatk_combinevariants_callers_to_combine:
  - gatk_variantrecalibration
picardtools_path: /usr/picard
qccollect_sampleinfo_file: cluster_constant_path!/case_id!/analysis_constant_path!/case_id!_qc_sample_info.yaml
vep_custom_annotation:
  genomic_superdups_frac_match:
    annotation_type: overlap
    force_report_coordinates: 0
    key: genomic_superdups_frac_match
    file_type: bed
    path: cluster_constant_path!/references/grch37_genomic_superdups_reformated_-20181009-.bed.gz
  clinvar:
    annotation_type: exact
    force_report_coordinates: 0
    key: CLINVAR
    file_type: vcf
    path: cluster_constant_path!/references/grch37_clinvar_reformated_-20220829-.vcf.gz
    vcf_fields: CLNSIG,CLNVID,CLNREVSTAT
vep_directory_cache: cluster_constant_path!/references/ensembl-tools-data-104/cache/
vep_plugins_dir_path: cluster_constant_path!/references/ensembl-tools-data-104/cache/Plugins
vep_plugin:
  dbNSFP:
    exist_check:
      - type: file
        path: cluster_constant_path!/references/grch37_dbnsfp_-v3.5a-.txt.gz
    parameters:
      - cluster_constant_path!/references/grch37_dbnsfp_-v3.5a-.txt.gz
      - GERP++_RS
      - GERP++_NR
      - phyloP100way_vertebrate
      - phastCons100way_vertebrate
      - REVEL_rankscore
  pLI:
    exist_check:
      - type: file
        path: cluster_constant_path!/references/gnomad_pli_per_gene_-_r2.1.1-.txt
    parameters:
      - cluster_constant_path!/references/gnomad_pli_per_gene_-_r2.1.1-.txt
  LoFtool:
    exist_check:
      - type: file
        path: cluster_constant_path!/references/ensembl-tools-data-104/cache/Plugins/LoFtool_scores.txt
    parameters:
      - cluster_constant_path!/references/ensembl-tools-data-104/cache/Plugins/LoFtool_scores.txt
  MaxEntScan:
    exist_check:
      - type: directory
        path: cluster_constant_path!/references/ensembl-tools-data-104/cache/Plugins/fordownload
    parameters:
      - cluster_constant_path!/references/ensembl-tools-data-104/cache/Plugins/fordownload
      - SWA
      - NCSS
  SpliceAI:
    exist_check:
      - type: file
        path: cluster_constant_path!/references/grch37_spliceai_scores_raw_indel_-v1.3-.vcf.gz
      - type: file
        path: cluster_constant_path!/references/grch37_spliceai_scores_raw_snv_-v1.3-.vcf.gz
    parameters:
      - snv=cluster_constant_path!/references/grch37_spliceai_scores_raw_snv_-v1.3-.vcf.gz
      - indel=cluster_constant_path!/references/grch37_spliceai_scores_raw_indel_-v1.3-.vcf.gz
