---
clusterConstantPath: /proj/b2010080/private
analysisConstantPath: analysis/nobackup
analysisType: exomes
outScriptDir: CLUSTERCONSTANTPATH!/ANALYSISTYPE!_scripts
GATKHaploTypeCallerRefBAMInfile: ReferenceBAMInfile.list
GATKVariantReCalibrationNumBadVariants: 3000
ImportantDbFile: dbCMMS.v1.0.txt
ImportantDbFileOutFile: 'CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!/FDN!/ALIGNER!/GATK/candidates/ranking/FDN!_orphan.selectVariants,CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!/FDN!/ALIGNER!/GATK/candidates/ranking/clinical/FDN!.selectVariants'
ImportantDbMasterFile: CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!.intersectCollect_selectVariants_db_master.txt
ImportantDbTemplate: select_dbCMMS_variants_db_master.txt
MIP: 1
QCCollectSampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
annovarPath: CLUSTERCONSTANTPATH!/modules/annovar
genomeAnalysisToolKitPath: CLUSTERCONSTANTPATH!/modules/GenomeAnalysisTK-2.8-1
inScriptDir: CLUSTERCONSTANTPATH!/mip_scripts_master
mergeAnnotatedVariantsTemplateFile: CMMS_intersectCollect_db_master_template.txt
outDataDir: CLUSTERCONSTANTPATH!/ANALYSISCONSTANTPATH!/ANALYSISTYPE!
pedigreeFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_pedigree.txt
picardToolsPath: CLUSTERCONSTANTPATH!/modules/picard-tools-1.106
projectID: b2010080
pythonVirtualEnvironment: virtualenv.py.2.7
referencesDir: CLUSTERCONSTANTPATH!/mip_references
sampleInfoFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_qc_sampleInfo.yaml
writeConfigFile: CLUSTERCONSTANTPATH!/ANALYSISTYPE!/FDN!/FDN!_config.yaml[INFO] 2016/04/15 01:09:28 MIPLogger - 1
[WARN] 2016/04/15 01:09:28 MIPLogger - 1
[ERROR] 2016/04/15 01:09:28 MIPLogger - 1
[FATAL] 2016/04/15 01:09:28 MIPLogger - 1
[INFO] 2016/04/15 01:09:29 MIPLogger - 1
[WARN] 2016/04/15 01:09:29 MIPLogger - 1
[ERROR] 2016/04/15 01:09:29 MIPLogger - 1
[FATAL] 2016/04/15 01:09:29 MIPLogger - 1
[INFO] 2016/04/15 01:10:07 MIPLogger - 1
[WARN] 2016/04/15 01:10:07 MIPLogger - 1
[ERROR] 2016/04/15 01:10:07 MIPLogger - 1
[FATAL] 2016/04/15 01:10:07 MIPLogger - 1
[INFO] 2016/04/15 01:10:08 MIPLogger - 1
[WARN] 2016/04/15 01:10:08 MIPLogger - 1
[ERROR] 2016/04/15 01:10:08 MIPLogger - 1
[FATAL] 2016/04/15 01:10:08 MIPLogger - 1
[INFO] 2016/04/15 01:10:13 MIPLogger - 1
[WARN] 2016/04/15 01:10:13 MIPLogger - 1
[ERROR] 2016/04/15 01:10:13 MIPLogger - 1
[FATAL] 2016/04/15 01:10:13 MIPLogger - 1
[INFO] 2016/04/15 01:10:14 MIPLogger - 1
[WARN] 2016/04/15 01:10:14 MIPLogger - 1
[ERROR] 2016/04/15 01:10:14 MIPLogger - 1
[FATAL] 2016/04/15 01:10:14 MIPLogger - 1
[INFO] 2016/04/15 01:10:38 MIPLogger - 1
[WARN] 2016/04/15 01:10:38 MIPLogger - 1
[ERROR] 2016/04/15 01:10:38 MIPLogger - 1
[FATAL] 2016/04/15 01:10:38 MIPLogger - 1
[INFO] 2016/04/15 01:10:39 MIPLogger - 1
[WARN] 2016/04/15 01:10:39 MIPLogger - 1
[ERROR] 2016/04/15 01:10:39 MIPLogger - 1
[FATAL] 2016/04/15 01:10:39 MIPLogger - 1
[INFO] 2016/04/25 15:08:38 MIPLogger - 1
[WARN] 2016/04/25 15:08:38 MIPLogger - 1
[ERROR] 2016/04/25 15:08:38 MIPLogger - 1
[FATAL] 2016/04/25 15:08:38 MIPLogger - 1
[INFO] 2016/04/25 15:08:39 MIPLogger - 1
[WARN] 2016/04/25 15:08:39 MIPLogger - 1
[ERROR] 2016/04/25 15:08:39 MIPLogger - 1
[FATAL] 2016/04/25 15:08:39 MIPLogger - 1
[INFO] 2016/04/25 15:10:37 MIPLogger - 1
[WARN] 2016/04/25 15:10:37 MIPLogger - 1
[ERROR] 2016/04/25 15:10:37 MIPLogger - 1
[FATAL] 2016/04/25 15:10:37 MIPLogger - 1
[INFO] 2016/04/25 15:10:37 MIPLogger - 1
[WARN] 2016/04/25 15:10:37 MIPLogger - 1
[ERROR] 2016/04/25 15:10:37 MIPLogger - 1
[FATAL] 2016/04/25 15:10:37 MIPLogger - 1
[INFO] 2016/04/25 15:14:36 MIPLogger - 1
[WARN] 2016/04/25 15:14:36 MIPLogger - 1
[ERROR] 2016/04/25 15:14:36 MIPLogger - 1
[FATAL] 2016/04/25 15:14:36 MIPLogger - 1
[INFO] 2016/04/25 15:14:37 MIPLogger - 1
[WARN] 2016/04/25 15:14:37 MIPLogger - 1
[ERROR] 2016/04/25 15:14:37 MIPLogger - 1
[FATAL] 2016/04/25 15:14:37 MIPLogger - 1
