---
bash_set_errexit: 1
bash_set_pipefail: 1
conda:
  python: 3.7
pip:
shell:
  mip_scripts:
    version: Your current MIP version
singularity:
  bwa:
    executable:
      bwa:
    uri: docker://clinicalgenomics/bwa:0.7.17
  bwakit:
    executable:
      bwa-postalt.js:
      fermi2:
      fermi2.pl:
      k8:
      ropebwt2:
      run-bwamem:
      run-HLA:
      typeHLA.js:
      typeHLA.sh:
      typeHLA-selctg.js:
      seqtk:
    uri: docker://clinicalgenomics/bwakit:0.7.15
  bedtools:
    executable:
      bedtools:
    uri: docker://clinicalgenomics/bedtools:2.2.29
  cadd:
    executable:
      CADD.sh:
    uri: shub://Clinical-Genomics/MIP:cadd-1.5
  cnvnator:
    executable:
      cnvnator:
      cnvnator2VCF.pl:
    uri: shub://Clinical-Genomics/MIP:cnvnator-0.4.1
  chanjo:
    executable:
      chanjo:
    uri: docker://clinicalgenomics/chanjo:4.2.0
  chromograph:
    executable:
      chromograph:
    uri: docker://clinicalgenomics/chromograph:91f0988
  expansionhunter:
    executable:
      ExpansionHunter:
    uri: docker://clinicalgenomics/expansionhunter:3.1.2
  fastqc:
    executable:
      fastqc:
    uri: docker://clinicalgenomics/fastqc:0.11.8
  delly:
    executable:
      delly:
    uri: shub://Clinical-Genomics/MIP:delly-0.8.1
  gatk:
    executable:
      gatk3: "no_executable_in_image"
    uri: shub://Clinical-Genomics/MIP:gatk-3.8
  gatk4:
    executable:
      gatk:
    uri: docker://broadinstitute/gatk:4.1.3.0
  genmod:
    executable:
      genmod:
    uri: docker://clinicalgenomics/genmod:3.7.3
  htslib:
    executable:
      bcftools:
      bgzip:
      samtools:
      tabix:
    uri: docker://clinicalgenomics/htslib:1.10.2
  manta:
    executable:
      configManta.py:
      runWorkflow.py: "no_executable_in_image"
    uri: docker://clinicalgenomics/manta:1.6.0
  multiqc:
    executable:
      multiqc:
    uri: docker://ewels/multiqc:v1.7
  peddy:
    executable:
      peddy: "python -m peddy"
    uri: docker://clinicalgenomics/peddy:0.4.3
  picard:
    executable:
      picard: "no_executable_in_image"
    uri: docker://broadinstitute/picard:2.22.0
  utilities:
    executable:
      pigz:
    uri: docker://clinicalgenomics/utilities:latest
  plink:
    executable:
      plink2:
    uri: docker://clinicalgenomics/plink:1.90b3.35
  rhocall:
    executable:
      rhocall:
    uri: docker://clinicalgenomics/rhocall:0.5.1
  rtg-tools:
    executable:
      rtg:
    uri: docker://realtimegenomics/rtg-tools:3.10.1
  sambamba:
    executable:
      sambamba:
    uri: docker://clinicalgenomics/sambamba:0.6.8
  smncopynumbercaller:
    executable:
      smn_caller.py:
    uri: docker://clinicalgenomics/smncopynumbercaller:4b2c1ad
  stranger:
    executable:
      stranger:
    uri: docker://clinicalgenomics/stranger:0.5.5
  svdb:
    executable:
      svdb:
    uri: shub://J35P312/SVDB:2.2.0
  tiddit:
    executable:
      TIDDIT.py:
    uri: shub://J35P312/TIDDIT:2.8.0
  ucsc:
    executable:
      wigToBigWig:
      bedToBigBed:
    uri: docker://clinicalgenomics/ucsc:357
  upd:
    executable:
      upd:
    uri: docker://clinicalgenomics/upd:0.1
  varg:
    executable:
      varg:
    uri: docker://clinicalgenomics/varg:1.2.0
  variant_integrity:
    executable:
      variant_integrity:
    uri: docker://clinicalgenomics/variant_integrity:0.0.4
  vcfanno:
    executable:
      vcfanno:
    uri: docker://clinicalgenomics/vcfanno:0.3.2
  vep:
    executable:
      vep:
    uri: docker://ensemblorg/ensembl-vep:release_97.4
  vcf2cytosure:
    executable:
      vcf2cytosure:
    uri: shub://J35P312/vcf2cytosure:0.5.1
  vt:
    executable:
      vt:
    uri: docker://clinicalgenomics/vt:2015.11.10
vep_plugins:
  - dbNSFP
  - ExACpLI
  - LoFtool
  - MaxEntScan
vep_auto_flag: cfp
