---
cluster_constant_path: /home/travis/build/henrikstranneheim/MIP/t/data
analysis_constant_path: analysis
java_use_large_pages: 1
outscript_dir: cluster_constant_path!/family_id!/analysis_constant_path!/scripts
gatk_genotypegvcfs_ref_gvcf: GRCh37_merged_reference_infiles_-2014-.gvcf
gatk_combinevariants_prioritize_caller: gatk,samtools,freebayes
qccollect_regexp_file: qc_regexp_-v1.13-.yaml
qccollect_sampleinfo_file: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_qc_sample_info.yaml
sambamba_depth_bed: GRCh37_scout_exons_-2017-01-.bed
gatk_path: cluster_constant_path!/modules/GenomeAnalysisTK-3.6
human_genome_reference: GRCh37_homo_sapiens_-d5-.fasta
script_dir: /mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/bin
core_processor_number: 16
outdata_dir: cluster_constant_path!/family_id!/analysis_constant_path!
pedigree_file: cluster_constant_path!/family_id!/family_id!_pedigree.yaml
picardtools_path: /home/travis/miniconda/envs/test_environment/bin
project_id: travis_test
reference_dir: cluster_constant_path!/references
sample_info_file: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_qc_sample_info.yaml
config_file_analysis: cluster_constant_path!/family_id!/analysis_constant_path!/family_id!_config.yaml
sv_vcfanno_lua: vcfanno_custom_-v1.0-.lua
sv_vcfanno_config: GRCh37_vcfanno_config_-v1.0-.toml
sv_vcfannotation_header_lines_file: vcfanno_headerLines_-v1.0-.txt
vep_directory_path: cluster_constant_path!/modules/miniconda2/envs/mip4.0/ensembl-tools-release-87/scripts/variant_effect_predictor
vep_directory_cache:  cluster_constant_path!/modules/miniconda2/envs/mip4.0/ensembl-tools-release-87/cache
vcfparser_vep_transcripts: 1
vcfparser_select_file: cluster_constant_path!/family_id!/aggregated_gene_panel_test.txt
vcfparser_select_file_matching_column: 3
sv_vcfparser_vep_transcripts: 1
sv_vcfparser_select_file: cluster_constant_path!/family_id!/aggregated_gene_panel_test.txt
sv_vcfparser_select_file_matching_column: 3
snpeff_path: /home/travis/miniconda/envs/test_environment/bin
snpsift_annotation_files:
  GRCh37_clinvar_-2017-01-04-.vcf.gz: CLNSIG,CLNACC,CLNREVSTAT
  GRCh37_exac_reheader_-r0.3.1-.vcf.gz: AF,MAX_AF
  GRCh37_anon-swegen_snp_-1000samples-.vcf.gz: AF,AC_Hom,AC_Het,AC_Hemi
  GRCh37_anon-swegen_indel_-1000samples-.vcf.gz: AF,AC_Hom,AC_Het,AC_Hemi
  GRCh37_loqusdb_-2016-09-26-.vcf.gz: Obs
  GRCh37_genbank_haplogroup_-2015-08-01-.vcf.gz: MTAF
snpsift_dbnsfp_annotations:
  - GERP++_RS
  - GERP++_NR
  - phyloP46way_primate
  - phyloP100way_vertebrate
  - phastCons46way_primate
  - phastCons100way_vertebrate
genmod_annotate_cadd_files:
  - GRCh37_cadd_whole_genome_snvs_ge10_-v1.3-.tsv.gz
  - GRCh37_cadd_1000g_phase3_-v1.3-.tsv.gz
  - GRCh37_cadd_exac_r0.3_-v1.3-.tsv.gz
genmod_models_reduced_penetrance_file: GRCh37_cust003-cmms-red-pen_-2017-.tsv 
genmod_annotate_spidex_file: GRCh37_spidex_public_noncommercial_-v1_0-.tab.gz
rank_model_file: rank_model_cmms_-v1.18-.ini
sv_genmod_models_family_type: cmms
sv_genmod_models_reduced_penetrance_file: GRCh37_cust003-cmms-red-pen_-2017-.tsv
sv_rank_model_file: svrank_model_cmms_-v1.0-.ini
source_environment_commands:
  - source
  - activate
  - test_environment
slurm_quality_of_service: low
