---

name: Publish bleeding edge to Docker Hub

"on":
  push:
    branches:
      - develop

jobs:
  docker-image-CI:
    name: Docker Image CI
    runs-on: ubuntu-latest
    steps:

      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Build and publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: clinicalgenomics/mip
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
